// Generated by CoffeeScript 1.9.1
(function() {
  var _, dd, emit;

  _ = require('underscore');

  dd = {
    views: {
      failures_by_retry_date: {
        map: function(doc) {
          var entry, i, len, nextAttemptTime, now, ref, ref1, ref2;
          now = +new Date();
          nextAttemptTime = 1e+100;
          ref = doc.audit || [];
          for (i = 0, len = ref.length; i < len; i++) {
            entry = ref[i];
            if (((ref1 = entry.attempts) != null ? ref1[0] : void 0) < nextAttemptTime) {
              nextAttemptTime = (ref2 = entry.attempts) != null ? ref2[0] : void 0;
            }
          }
          if (nextAttemptTime < 1e+100) {
            return emit(nextAttemptTime);
          }
        }
      },
      audit_by_timestamp: {
        map: function(doc) {
          var entry, i, len, out, ref, results, typ;
          ref = doc.audit;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            entry = ref[i];
            typ = doc._id.indexOf('team_') === 0 ? 'team' : 'user';
            out = {
              _id: doc._id,
              name: doc.name,
              entry: entry,
              type: typ
            };
            results.push(emit(entry.dt, out));
          }
          return results;
        }
      }
    },
    lists: {
      get_values: function(header, req) {
        var out, row, val;
        out = [];
        while ((row = getRow())) {
          val = row.value;
          out.push(val);
        }
        return JSON.stringify(out);
      }
    },
    rewrites: [
      {
        from: "/audit",
        to: "/_list/get_values/audit_by_timestamp",
        query: {}
      }
    ],
    shows: {},
    updates: {}
  };

  if (typeof emit === 'undefined') {
    dd.emitted = [];
    emit = function(k, v) {
      return dd.emitted.push([k, v]);
    };
  }

  module.exports = dd;

}).call(this);
