// Generated by CoffeeScript 1.9.1
(function() {
  var _, a;

  _ = require('underscore');

  a = {
    views: {
      audit_by_timestamp: {
        map: function(doc) {
          var entry, i, len, out, ref, results, typ;
          ref = doc.audit;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            entry = ref[i];
            typ = doc._id.indexOf('team_') === 0 ? 'team' : 'user';
            out = {
              _id: doc._id,
              name: doc.name,
              entry: entry,
              type: typ
            };
            results.push(emit(entry.dt, out));
          }
          return results;
        }
      }
    },
    lists: {
      get_values: function(header, req) {
        var out, row, val;
        out = [];
        while ((row = getRow())) {
          val = row.value;
          out.push(val);
        }
        return JSON.stringify(out);
      }
    },
    rewrites: [
      {
        from: "/audit",
        to: "/_list/get_values/audit_by_timestamp",
        query: {}
      }
    ],
    mixin: function(dd) {
      _.extend(dd.views, a.views);
      _.extend(dd.lists, a.lists);
      dd.rewrites = dd.rewrites.concat(a.rewrites);
      return dd;
    }
  };

  module.exports = a;

}).call(this);
