// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  var h, _;

  _ = require('underscore');

  h = {};

  module.exports = function(shared, getRow, start, send) {
    h.JSONResponse = function(doc) {

      /*
      format a proper JSON response for the document
       */
      return {
        headers: {
          'Content-Type': "application/json"
        },
        body: JSON.stringify(doc)
      };
    };
    h.sendNakedList = function(rowTransform) {

      /*
      lazily send a JSON serialized list of rows,
      each having been transformed by rowTransform.
      If rowTransform throws the string `"skip"`,
      the row will be skipped.
       */
      var e, first, row, transformedRow;
      start({
        headers: {
          'Content-Type': 'application/json'
        }
      });
      first = true;
      send('[');
      while ((row = getRow())) {
        try {
          transformedRow = rowTransform(row);
        } catch (_error) {
          e = _error;
          if (e === 'skip') {
            continue;
          } else {
            throw e;
          }
        }
        if (first) {
          first = false;
        } else {
          send(',');
        }
        send(JSON.stringify(transformedRow));
      }
      return send(']');
    };
    h.listGenerators = {
      get_prepped_of_type: function(docType) {

        /*
        returns a list function
        must call with {get_docs: true}
        only return documents of the specified type
        run all document through the appropriate prepDoc function defined in shared.prepDocFns
         */
        return function(header, req) {
          return h.sendNakedList(function(row) {
            var doc;
            doc = row.doc;
            if (shared.getDocType(doc) !== docType) {
              throw 'skip';
            }
            return shared.prepDoc(doc);
          });
        };
      }
    };
    h.lists = {
      get_prepped: function(header, req) {

        /*
        must call with {get_docs: true}
        run all document through the appropriate prepDoc function defined in shared.prepDocFns
         */
        return h.sendNakedList(function(row) {
          return shared.prepDoc(row.doc);
        });
      },
      get_values: function(header, req) {

        /*
        return only the value from the passed view's map function
         */
        return h.sendNakedList(function(row) {
          return row.value;
        });
      },
      get_first_prepped: function(header, req) {

        /*
        must call with {get_docs: true}
        get the first returned document and run it through the prepDoc function
         */
        var row;
        row = getRow();
        if (row) {
          return h.shows.get_prepped(row.doc);
        } else {
          throw ['error', 'not_found', 'document matching query does not exist'];
        }
      }
    };
    h.shows = {
      get_prepped: function(doc, req) {

        /*
        return the document after running through shared.prepDoc
         */
        var preppedDoc;
        preppedDoc = shared.prepDoc(doc);
        return h.JSONResponse(preppedDoc);
      }
    };
    return h;
  };

}).call(this);
