// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(app, dbNames, couch_utils, routePrefix) {

    /*
    app: the express app
    dbNames: list of all dbs to query for audit entries
    routePrefix: optional prefix for route (e.g.: /kratos, /moirai)
     */
    var audit;
    audit = require('./api/audit')(dbNames);
    routePrefix || (routePrefix = '');
    return app.get(routePrefix + '/audit', audit.handleGetAudit(dbNames, couch_utils));
  };

}).call(this);
