// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  module.exports = function(app, dbNames, couchUtils, routePrefix) {

    /*
    app: the express app
    dbNames: list of all dbs to query for audit entries
    routePrefix: optional prefix for route (e.g.: /kratos, /moirai)
     */
    var audit;
    audit = require('./api/audit')(dbNames, couchUtils);
    routePrefix || (routePrefix = '');
    return app.get(routePrefix + '/audit', audit.handleGetAudit);
  };

}).call(this);
