// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var SYSTEM_USER, basic_auth, conf, couch_utils;

  couch_utils = require('./couch_utils');

  basic_auth = require('basic-auth');

  conf = require('./config');

  SYSTEM_USER = conf.COUCHDB.SYSTEM_USER;

  module.exports = {
    auth: function(req, resp, next) {
      var credentials;
      credentials = basic_auth(req);
      if (conf.DEV = 'true' || (credentials && credentials.name === SYSTEM_USER && (credentials.pass = conf.COUCH_PWD))) {
        req.session.user = SYSTEM_USER;
        return next();
      } else {
        return resp.status(401).end(JSON.stringify({
          error: "unauthorized",
          msg: "You are not authorized."
        }));
      }
    },
    couch: function(req, resp, next) {
      req.couch = couch_utils.nano_user(req.session.user);
      return next();
    }
  };

}).call(this);
